name: Run main.py daily

on:
  schedule:
    - cron: '30 0 * * *'  # Runs at 5:30 PM Vancouver time (UTC-7 or UTC-8 depending on DST)

  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check if the URL is reachable
        run: |
            curl -L https://eg-srvr4.evergreen-home.com/app/portal

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
            SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
            EVERGREEN_PASS: ${{ secrets.EVERGREEN_PASS }}
            EVERGREEN_USER: ${{ secrets.EVERGREEN_USER }}
            EVERGREEN_QUESTION1: ${{ secrets.EVERGREEN_QUESTION1 }}
            EVERGREEN_QUESTION2: ${{ secrets.EVERGREEN_QUESTION2 }}
            GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
        run: python main.py
